
// ------------------------------------------------------------------------------------------------
// Copyright 2023 by Heqing Huang (feipenghhq@gamil.com)
// ------------------------------------------------------------------------------------------------
// Generated by ParallelLFSR.py
// ------------------------------------------------------------------------------------------------
// Polynomial: 0x6801
// LFSR width: 16
// Data width: 0
// ------------------------------------------------------------------------------------------------

module lfsr_0x6801_W16_D0  (
    input  logic [16-1:0]    lfsr_in,
    output logic [16-1:0]    lfsr_out
);

assign lfsr_out[0] = lfsr_in[0] ^ lfsr_in[2] ^ lfsr_in[3] ^ lfsr_in[4] ^ lfsr_in[5] ^ lfsr_in[7] ^ lfsr_in[12] ^ lfsr_in[14] ^ lfsr_in[15];
assign lfsr_out[1] = lfsr_in[1] ^ lfsr_in[3] ^ lfsr_in[4] ^ lfsr_in[5] ^ lfsr_in[6] ^ lfsr_in[8] ^ lfsr_in[13] ^ lfsr_in[15];
assign lfsr_out[2] = lfsr_in[2] ^ lfsr_in[4] ^ lfsr_in[5] ^ lfsr_in[6] ^ lfsr_in[7] ^ lfsr_in[9] ^ lfsr_in[14];
assign lfsr_out[3] = lfsr_in[3] ^ lfsr_in[5] ^ lfsr_in[6] ^ lfsr_in[7] ^ lfsr_in[8] ^ lfsr_in[10] ^ lfsr_in[15];
assign lfsr_out[4] = lfsr_in[4] ^ lfsr_in[6] ^ lfsr_in[7] ^ lfsr_in[8] ^ lfsr_in[9] ^ lfsr_in[11];
assign lfsr_out[5] = lfsr_in[5] ^ lfsr_in[7] ^ lfsr_in[8] ^ lfsr_in[9] ^ lfsr_in[10] ^ lfsr_in[12];
assign lfsr_out[6] = lfsr_in[6] ^ lfsr_in[8] ^ lfsr_in[9] ^ lfsr_in[10] ^ lfsr_in[11] ^ lfsr_in[13];
assign lfsr_out[7] = lfsr_in[7] ^ lfsr_in[9] ^ lfsr_in[10] ^ lfsr_in[11] ^ lfsr_in[12] ^ lfsr_in[14];
assign lfsr_out[8] = lfsr_in[8] ^ lfsr_in[10] ^ lfsr_in[11] ^ lfsr_in[12] ^ lfsr_in[13] ^ lfsr_in[15];
assign lfsr_out[9] = lfsr_in[9] ^ lfsr_in[11] ^ lfsr_in[12] ^ lfsr_in[13] ^ lfsr_in[14];
assign lfsr_out[10] = lfsr_in[10] ^ lfsr_in[12] ^ lfsr_in[13] ^ lfsr_in[14] ^ lfsr_in[15];
assign lfsr_out[11] = lfsr_in[0] ^ lfsr_in[2] ^ lfsr_in[3] ^ lfsr_in[4] ^ lfsr_in[5] ^ lfsr_in[7] ^ lfsr_in[11] ^ lfsr_in[12] ^ lfsr_in[13];
assign lfsr_out[12] = lfsr_in[1] ^ lfsr_in[3] ^ lfsr_in[4] ^ lfsr_in[5] ^ lfsr_in[6] ^ lfsr_in[8] ^ lfsr_in[12] ^ lfsr_in[13] ^ lfsr_in[14];
assign lfsr_out[13] = lfsr_in[0] ^ lfsr_in[3] ^ lfsr_in[6] ^ lfsr_in[9] ^ lfsr_in[12] ^ lfsr_in[13];
assign lfsr_out[14] = lfsr_in[0] ^ lfsr_in[1] ^ lfsr_in[2] ^ lfsr_in[3] ^ lfsr_in[5] ^ lfsr_in[10] ^ lfsr_in[12] ^ lfsr_in[13] ^ lfsr_in[15];
assign lfsr_out[15] = lfsr_in[1] ^ lfsr_in[2] ^ lfsr_in[3] ^ lfsr_in[4] ^ lfsr_in[6] ^ lfsr_in[11] ^ lfsr_in[13] ^ lfsr_in[14];


endmodule